### ISSUE TITLE
Deadlocking issue

### ISSUE THREAD

**Issue by pmiddleton** [CollabIP/Tethr.AudioBroker.SDK#3]
You are using .GetAwaiter().GetResult() in GetApiAuthToken in order to run an async method sync.  This can cause a deadlock if a synchronization context is in play.  

See these articles.  

https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by AdamCLarsen** [comment]
Good find, added a call to Configure Await that should solve the deadlocking issue.  Build https://www.nuget.org/packages/Tethr.AudioBroker/1.2.0-beta07 contains the fix, let us know if you still see any deadlocks.

**Comment by pmiddleton** [comment]
Unfortunately as the articles point out ConfigureAwait only solves the issue if everyone in the call chain uses it.  In this case HttpClient does not so this won't fix the issue.

You should expose a public async authenticate method which the consuming code can await on.  

If you want to continue automatically authenticating and allow multithreaded apps to not over call the authenticate api you should look at using an AsyncLazy.  See https://blogs.msdn.microsoft.com/pfxteam/2011/01/15/asynclazyt/
